model: LorentzNet

dataset: TopDataset

augmentation_params:
    p: 0.5
    max_beta: 1
    rotation: True

n_hidden: 72
dropout: 0.2
n_layers: 6
c_weight: 0.005
learning_rate: 0.001
weight_decay: 0.01
batch_size: 128
use_scheduler: True
