model: ParticleNet

conv_params:
- [16, [64, 64, 64]]
- [16, [128, 128, 128]]
- [16, [256, 256, 256]]

fc_params:
- [0.1, 256]

dataset: QGDataset
dataset_params:
    n_limit: -1
    pid: True

augmentation_params:
    p: 0.5
    max_beta: 1
    rotation: True
    pid: True

input_size: 10
output_size: 2
learning_rate: 0.00003
lorentz_aug: True
batch_size: 256
is_classification: True
use_scheduler: True
